# Generated by Django 5.1.2 on 2024-10-31 13:13

import django.db.models.deletion
import uuid
import xy_django_app_siteuser.abstracts
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Information", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MAuthUserCredential",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "platform",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="平台名称"
                    ),
                ),
                (
                    "open_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="open_id"
                    ),
                ),
                (
                    "union_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="union_id"
                    ),
                ),
                (
                    "app_key",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="app_key"
                    ),
                ),
                (
                    "app_secret",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="app_secret"
                    ),
                ),
                (
                    "mobile",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="手机号"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MCaptcha",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "code",
                    models.CharField(
                        default="",
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="验证码",
                    ),
                ),
                (
                    "create_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "signature",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="标签",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MEmailCaptcha",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "code",
                    models.CharField(
                        default="",
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="验证码",
                    ),
                ),
                (
                    "create_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "signature",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="标签",
                    ),
                ),
                (
                    "from_email",
                    models.CharField(max_length=255, verbose_name="发送方邮箱"),
                ),
                ("to_email", models.CharField(max_length=255, verbose_name="目标邮箱")),
            ],
        ),
        migrations.CreateModel(
            name="MEmailCredential",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "email_address",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="邮箱"
                    ),
                ),
                (
                    "email_password",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="邮箱密码"
                    ),
                ),
                (
                    "email_host",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="邮箱主机地址",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MSMSCaptcha",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "code",
                    models.CharField(
                        default="",
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="验证码",
                    ),
                ),
                (
                    "create_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "signature",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="标签",
                    ),
                ),
                ("mobile", models.CharField(max_length=255, verbose_name="手机号")),
            ],
        ),
        migrations.CreateModel(
            name="MSMSCaptchaCredential",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="平台名称"
                    ),
                ),
                (
                    "app_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="app_id"
                    ),
                ),
                (
                    "app_key",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="app_key"
                    ),
                ),
                (
                    "app_secret",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="app_secret"
                    ),
                ),
                (
                    "template_id",
                    models.IntegerField(blank=True, null=True, verbose_name="模板ID"),
                ),
                (
                    "sign",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="签名"
                    ),
                ),
                (
                    "options_config",
                    models.TextField(blank=True, null=True, verbose_name="其他配置"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MAuthUser",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "date_of_birth",
                    models.DateTimeField(auto_now=True, null=True, verbose_name="生日"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        blank=True, default=True, null=True, verbose_name="是否启用"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=255, null=True, verbose_name="邮箱"
                    ),
                ),
                (
                    "mobile",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="手机号"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        null=True,
                        verbose_name="用户名",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        null=True,
                        verbose_name="姓名",
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        null=True,
                        verbose_name="密码",
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        blank=True,
                        choices=[("man", "男"), ("female", "女"), ("unknown", "未知")],
                        default="unknown",
                        max_length=15,
                        null=True,
                        verbose_name="性别",
                    ),
                ),
                (
                    "thumb",
                    models.ImageField(
                        blank=True,
                        default="",
                        null=True,
                        upload_to=xy_django_app_siteuser.abstracts.user__thumbnails,
                        verbose_name="头像",
                    ),
                ),
                (
                    "age",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="年龄"
                    ),
                ),
                (
                    "expires_time",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="登陆过期时间"
                    ),
                ),
                (
                    "nickname",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        null=True,
                        verbose_name="昵称",
                    ),
                ),
                (
                    "userid",
                    models.UUIDField(
                        blank=True,
                        default=uuid.uuid4,
                        null=True,
                        unique=True,
                        verbose_name="用户ID",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(
                        blank=True,
                        default=uuid.uuid4,
                        null=True,
                        unique=True,
                        verbose_name="token",
                    ),
                ),
                (
                    "validation_token",
                    models.UUIDField(
                        blank=True,
                        default=uuid.uuid4,
                        null=True,
                        unique=True,
                        verbose_name="验证token",
                    ),
                ),
                (
                    "validation_expires_time",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="验证过期时间"
                    ),
                ),
                (
                    "idcard_no",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="身份证号"
                    ),
                ),
                (
                    "platform_userid",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="平台用户id"
                    ),
                ),
                (
                    "user_secret",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="平台用户密钥"
                    ),
                ),
                (
                    "auth_token",
                    models.CharField(max_length=255, unique=True, verbose_name="token"),
                ),
                (
                    "refresh_token",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="refresh_token"
                    ),
                ),
                (
                    "openid",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="openid"
                    ),
                ),
                (
                    "appid",
                    models.CharField(max_length=255, unique=True, verbose_name="appid"),
                ),
                (
                    "identifier",
                    models.UUIDField(
                        blank=True,
                        default=uuid.uuid4,
                        null=True,
                        unique=True,
                        verbose_name="唯一标识",
                    ),
                ),
                (
                    "credential",
                    models.ForeignKey(
                        max_length=255,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_credential",
                        to="SiteUser.mauthusercredential",
                        verbose_name="授权用户凭证",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MSiteUser",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "date_of_birth",
                    models.DateTimeField(auto_now=True, null=True, verbose_name="生日"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        blank=True, default=True, null=True, verbose_name="是否启用"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=255, null=True, verbose_name="邮箱"
                    ),
                ),
                (
                    "mobile",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="手机号"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        null=True,
                        verbose_name="用户名",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        null=True,
                        verbose_name="姓名",
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        null=True,
                        verbose_name="密码",
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        blank=True,
                        choices=[("man", "男"), ("female", "女"), ("unknown", "未知")],
                        default="unknown",
                        max_length=15,
                        null=True,
                        verbose_name="性别",
                    ),
                ),
                (
                    "thumb",
                    models.ImageField(
                        blank=True,
                        default="",
                        null=True,
                        upload_to=xy_django_app_siteuser.abstracts.user__thumbnails,
                        verbose_name="头像",
                    ),
                ),
                (
                    "age",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="年龄"
                    ),
                ),
                (
                    "expires_time",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="登陆过期时间"
                    ),
                ),
                (
                    "nickname",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        null=True,
                        verbose_name="昵称",
                    ),
                ),
                (
                    "userid",
                    models.UUIDField(
                        blank=True,
                        default=uuid.uuid4,
                        null=True,
                        unique=True,
                        verbose_name="用户ID",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(
                        blank=True,
                        default=uuid.uuid4,
                        null=True,
                        unique=True,
                        verbose_name="token",
                    ),
                ),
                (
                    "validation_token",
                    models.UUIDField(
                        blank=True,
                        default=uuid.uuid4,
                        null=True,
                        unique=True,
                        verbose_name="验证token",
                    ),
                ),
                (
                    "validation_expires_time",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="验证过期时间"
                    ),
                ),
                (
                    "idcard_no",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="身份证号"
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_region",
                        to="Information.mregion",
                        verbose_name="所在地",
                    ),
                ),
            ],
        ),
    ]
