# Generated by Django 5.1.2 on 2024-10-31 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MRegion",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=180, null=True, verbose_name="名称"
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        blank=True, max_length=180, null=True, verbose_name="语言"
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True, max_length=180, null=True, verbose_name="地区"
                    ),
                ),
                (
                    "region_code",
                    models.CharField(
                        blank=True, max_length=180, null=True, verbose_name="地区代号"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, max_length=180, null=True, verbose_name="国家"
                    ),
                ),
                (
                    "country_code",
                    models.CharField(
                        blank=True, max_length=180, null=True, verbose_name="国家代号"
                    ),
                ),
                (
                    "province",
                    models.CharField(
                        blank=True, max_length=180, null=True, verbose_name="省份"
                    ),
                ),
                (
                    "province_code",
                    models.CharField(
                        blank=True, max_length=180, null=True, verbose_name="省份代号"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=180, null=True, verbose_name="城市"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=180, null=True, verbose_name="地址"
                    ),
                ),
                (
                    "town",
                    models.CharField(
                        blank=True, max_length=180, null=True, verbose_name="镇"
                    ),
                ),
                (
                    "district",
                    models.CharField(
                        blank=True, max_length=180, null=True, verbose_name="区域"
                    ),
                ),
                (
                    "full_address",
                    models.CharField(
                        blank=True, max_length=180, null=True, verbose_name="全部地址"
                    ),
                ),
                (
                    "latitude",
                    models.FloatField(
                        blank=True, max_length=180, null=True, verbose_name="经度"
                    ),
                ),
                (
                    "longitude",
                    models.FloatField(
                        blank=True, max_length=180, null=True, verbose_name="纬度"
                    ),
                ),
            ],
            options={
                "verbose_name": "地理信息",
                "verbose_name_plural": "地理信息",
            },
        ),
    ]
